### ISSUE TITLE
Command does not work 

### ISSUE THREAD

**Issue by notfifteen** [Artillex-Studios/AxVaults#3]
/axvaultsadmin delete Not working

I would love for them to add support for offline users, when a user is not connected the /axvaultsadmin view command does not work, it returns an invalid player message
![image](https://github.com/Artillex-Studios/AxVaults/assets/75852372/36564e02-2fd1-4d25-a31f-8db4f0528556)

[18:03:09 INFO]: AxVaults version 1.0.3

**Comment by BenceX100** [comment]
I think this was fixed a while ago, if not, feel free to reopen
